#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80
# Querying Nginx at its root (/) with a GET request (requesting a page)
# 	   curl http://54.144.83.44/   --> returns string "Hello World!"
#	   curl http://54.144.83.44/   --> returns header info

sudo apt-get -y update
sudo apt-get -y install nginx
sed -i "21s/^listen .*/listen 80" /etc/nginx/sites-enabled/defult
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx start
